exports.EditProfileCurrentEmailAddress = "hebanassif19@gmail.com";
exports.EditProfileCurrentEmailPassword = "123456";
exports.EditProfileCurrentUsername = "heba";
exports.EditProfileCurrentGender = "F";
exports.EditProfileCurrenDateOfbirth = "1999-03-03";
exports.EditProfileTestEmailAddress = "maram311999@hotmail.com";
exports.EditProfileTestEmailPassword = "MaramHosni31";
exports.AccountEmailAddress="ayaelsackaan.1999@gmail.com";
exports.AccountPassword="222";